# Generated by Django 6.0.5 on 2026-05-30 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_remove_booking_promo_code'),
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Mã khuyến mãi')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Mô tả')),
                ('discount_type', models.CharField(choices=[('percent', 'Giảm theo %'), ('flat', 'Giảm số tiền cố định (VND)')], max_length=10, verbose_name='Loại giảm giá')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Giá trị giảm')),
                ('start_date', models.DateTimeField(verbose_name='Ngày bắt đầu')),
                ('end_date', models.DateTimeField(verbose_name='Ngày kết thúc')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
            ],
            options={
                'verbose_name': 'Mã khuyến mãi',
                'verbose_name_plural': 'Danh sách mã khuyến mãi',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='PromoCode',
        ),
    ]
