# Generated by Django 6.0.5 on 2026-05-31 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0004_booking_promotion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('cash', 'Tiền mặt'), ('momo', 'MoMo (giả lập)'), ('banking', 'Chuyển khoản (giả lập)')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Chờ thanh toán'), ('success', 'Thành công'), ('failed', 'Thất bại')], default='pending', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='bookings.booking')),
            ],
        ),
    ]
