# Generated by Django 6.0.5 on 2026-05-31 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cash', 'Tiền mặt'), ('momo', 'MoMo'), ('banking', 'Chuyển khoản')], max_length=20),
        ),
    ]
