# Generated by Django 6.0.5 on 2026-05-28 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên sân')),
                ('court_type', models.CharField(choices=[('badminton', 'Cầu lông'), ('football', 'Bóng đá'), ('pickleball', 'Pickleball'), ('basketball', 'Bóng rổ'), ('tennis', 'Tennis')], max_length=20, verbose_name='Loại sân')),
                ('address', models.CharField(max_length=300, verbose_name='Địa chỉ')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('price_per_hour', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Giá thuê/giờ (VNĐ)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='courts/', verbose_name='Ảnh sân')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courts', to=settings.AUTH_USER_MODEL, verbose_name='Chủ sân')),
            ],
            options={
                'verbose_name': 'Sân',
                'verbose_name_plural': 'Danh sách sân',
                'ordering': ['-created_at'],
            },
        ),
    ]
