# Generated by Django 6.0.5 on 2026-05-28 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='court',
            name='district',
            field=models.CharField(blank=True, choices=[('cau_giay', 'Cầu Giấy'), ('dong_da', 'Đống Đa'), ('hai_ba_trung', 'Hai Bà Trưng'), ('hoan_kiem', 'Hoàn Kiếm'), ('thanh_xuan', 'Thanh Xuân'), ('ha_dong', 'Hà Đông'), ('bac_tu_liem', 'Bắc Từ Liêm'), ('nam_tu_liem', 'Nam Từ Liêm'), ('khac', 'Khác')], default='khac', max_length=20, verbose_name='Quận/Huyện'),
        ),
    ]
