# Generated by Django 6.0.5 on 2026-05-30 08:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courts', '0003_favorite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Điểm đánh giá (1–5)')),
                ('comment', models.TextField(max_length=500, verbose_name='Nhận xét')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đánh giá')),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='courts.court', verbose_name='Sân')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người đánh giá')),
            ],
            options={
                'verbose_name': 'Đánh giá',
                'verbose_name_plural': 'Danh sách đánh giá',
                'ordering': ['-created_at'],
                'unique_together': {('court', 'user')},
            },
        ),
    ]
