# Generated by Django 6.0.5 on 2026-05-30 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_discount_amount_booking_promo_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='promo_code',
        ),
    ]
