# Generated by Django 6.0.5 on 2026-05-30 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_remove_booking_promo_code'),
        ('promotions', '0002_promotion_delete_promocode'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='promotions.promotion', verbose_name='Mã khuyến mãi'),
        ),
    ]
