# Generated by Django 6.0.5 on 2026-06-08 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_promotion'),
        ('courts', '0004_alter_court_owner'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('court', 'date', 'start_time')},
        ),
    ]
